### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by liubo20210831** [aws/jsii#3589]
### Describe the bug

The CDK code has syntax errors in jsii-1.6. Among the several versions I have used, the 1.58 and 1.59 versions have no problem

### Expected Behavior

There should be no error when executing the CDK synth command

### Current Behavior

When I use AWS CDK to deploy AWS resources, the following error occurs when I execute the CDK synth command
```
$ cdk synth *****
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                  !!
!!  Node v13.7.0 has reached end-of-life and is not supported.                      !!
!!  You may to encounter runtime issues, and should switch to a supported release.  !!
!!                                                                                  !!
!!  As of the current release, supported versions of node are:                      !!
!!  - ^12.7.0                                                                       !!
!!  - ^14.5.0                                                                       !!
!!  - ^16.3.0                                                                       !!
!!                                                                                  !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(node:89) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
b'/tmp/tmpc5cle4yu/bin/jsii-runtime.js:3666\n'
b'                this.untested = opts.untested ?? false;\n'
b'                                               ^\n'
b'\n'
b"SyntaxError: Unexpected token '?'\n"
b'    at wrapSafe (internal/modules/cjs/loader.js:1067:16)\n'
b'    at Module._compile (internal/modules/cjs/loader.js:1115:27)\n'
b'    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)\n'
b'    at Module.load (internal/modules/cjs/loader.js:1000:32)\n'
b'    at Function.Module._load (internal/modules/cjs/loader.js:899:14)\n'
b'    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n'
b'    at internal/main/run_main_module.js:17:47\n'
```

### Reproduction Steps

```
npm install -g aws-cdk@2.3.0
/usr/bin/cdk -> /usr/lib/node_modules/aws-cdk/bin/cdk
npm WARN notsup Unsupported engine for aws-cdk@2.3.0: wanted: {"node":">= 14.15.0"} (current: {"node":"13.7.0","npm":"6.13.6"})
npm WARN notsup Not compatible with your version of node/npm: aws-cdk@2.3.0
+ aws-cdk@2.3.0
added 43 packages from 67 contributors, removed 82 packages and updated 83 packages in 16.62s
$ python -m pip install --upgrade pip
Collecting pip
  Downloading pip-22.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-22.1.2
$ pip install aws-cdk.core==1.138.0 aws-cdk.aws-ecs==1.138.0 aws_cdk.aws_logs==1.138.0 aws_cdk.aws_ecs_patterns==1.138.0 aws_cdk.aws_applicationautoscaling==1.138.0  boto3==1.24.0 PyYAML
Collecting aws-cdk.core==1.138.0
  Downloading aws_cdk.core-1.138.0-py3-none-any.whl (1.2 MB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 1.2/1.2 MB 27.4 MB/s eta 0:00:00
Collecting aws-cdk.aws-ecs==1.138.0
  Downloading aws_cdk.aws_ecs-1.138.0-py3-none-any.whl (878 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 878.7/878.7 kB 36.8 MB/s eta 0:00:00
Collecting aws_cdk.aws_logs==1.138.0
  Downloading aws_cdk.aws_logs-1.138.0-py3-none-any.whl (164 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 164.3/164.3 kB 24.9 MB/s eta 0:00:00
Collecting aws_cdk.aws_ecs_patterns==1.138.0
  Downloading aws_cdk.aws_ecs_patterns-1.138.0-py3-none-any.whl (250 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 250.6/250.6 kB 28.9 MB/s eta 0:00:00
Collecting aws_cdk.aws_applicationautoscaling==1.138.0
  Downloading aws_cdk.aws_applicationautoscaling-1.138.0-py3-none-any.whl (175 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 175.7/175.7 kB 30.2 MB/s eta 0:00:00
Collecting boto3==1.24.0
  Downloading boto3-1.24.0-py3-none-any.whl (132 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 132.5/132.5 kB 17.9 MB/s eta 0:00:00
Collecting PyYAML
  Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 701.2/701.2 kB 36.5 MB/s eta 0:00:00
Collecting publication>=0.0.3
  Downloading publication-0.0.3-py2.py3-none-any.whl (7.7 kB)
Collecting jsii<2.0.0,>=1.50.0
  Downloading jsii-1.60.0-py3-none-any.whl (520 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 521.0/521.0 kB 43.4 MB/s eta 0:00:00
Collecting aws-cdk.cx-api==1.138.0
  Downloading aws_cdk.cx_api-1.138.0-py3-none-any.whl (150 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 150.5/150.5 kB 23.4 MB/s eta 0:00:00
Collecting aws-cdk.region-info==1.138.0
  Downloading aws_cdk.region_info-1.138.0-py3-none-any.whl (90 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 90.3/90.3 kB 14.1 MB/s eta 0:00:00
Collecting constructs<4.0.0,>=3.3.69
  Downloading constructs-3.4.32-py3-none-any.whl (67 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 67.3/67.3 kB 10.3 MB/s eta 0:00:00
Collecting aws-cdk.cloud-assembly-schema==1.138.0
  Downloading aws_cdk.cloud_assembly_schema-1.138.0-py3-none-any.whl (150 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 150.9/150.9 kB 22.4 MB/s eta 0:00:00
Collecting aws-cdk.aws-s3==1.138.0
  Downloading aws_cdk.aws_s3-1.138.0-py3-none-any.whl (440 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 440.8/440.8 kB 38.4 MB/s eta 0:00:00
Collecting aws-cdk.aws-ecr==1.138.0
  Downloading aws_cdk.aws_ecr-1.138.0-py3-none-any.whl (106 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 106.3/106.3 kB 20.4 MB/s eta 0:00:00
Collecting aws-cdk.aws-autoscaling-hooktargets==1.138.0
  Downloading aws_cdk.aws_autoscaling_hooktargets-1.138.0-py3-none-any.whl (26 kB)
Collecting aws-cdk.aws-elasticloadbalancing==1.138.0
  Downloading aws_cdk.aws_elasticloadbalancing-1.138.0-py3-none-any.whl (91 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 91.8/91.8 kB 16.5 MB/s eta 0:00:00
Collecting aws-cdk.aws-ssm==1.138.0
  Downloading aws_cdk.aws_ssm-1.138.0-py3-none-any.whl (216 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 216.0/216.0 kB 30.3 MB/s eta 0:00:00
Collecting aws-cdk.aws-ecr-assets==1.138.0
  Downloading aws_cdk.aws_ecr_assets-1.138.0-py3-none-any.whl (67 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 67.9/67.9 kB 12.7 MB/s eta 0:00:00
Collecting aws-cdk.aws-secretsmanager==1.138.0
  Downloading aws_cdk.aws_secretsmanager-1.138.0-py3-none-any.whl (175 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 175.4/175.4 kB 27.8 MB/s eta 0:00:00
Collecting aws-cdk.aws-sqs==1.138.0
  Downloading aws_cdk.aws_sqs-1.138.0-py3-none-any.whl (98 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 98.0/98.0 kB 13.8 MB/s eta 0:00:00
Collecting aws-cdk.aws-s3-assets==1.138.0
  Downloading aws_cdk.aws_s3_assets-1.138.0-py3-none-any.whl (44 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 44.2/44.2 kB 7.8 MB/s eta 0:00:00
Collecting aws-cdk.aws-elasticloadbalancingv2==1.138.0
  Downloading aws_cdk.aws_elasticloadbalancingv2-1.138.0-py3-none-any.whl (476 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 476.7/476.7 kB 36.4 MB/s eta 0:00:00
Collecting aws-cdk.aws-certificatemanager==1.138.0
  Downloading aws_cdk.aws_certificatemanager-1.138.0-py3-none-any.whl (273 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 273.0/273.0 kB 30.4 MB/s eta 0:00:00
Collecting aws-cdk.aws-servicediscovery==1.138.0
  Downloading aws_cdk.aws_servicediscovery-1.138.0-py3-none-any.whl (143 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 143.3/143.3 kB 21.7 MB/s eta 0:00:00
Collecting aws-cdk.aws-autoscaling==1.138.0
  Downloading aws_cdk.aws_autoscaling-1.138.0-py3-none-any.whl (451 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 451.8/451.8 kB 34.5 MB/s eta 0:00:00
Collecting aws-cdk.aws-ec2==1.138.0
  Downloading aws_cdk.aws_ec2-1.138.0-py3-none-any.whl (1.7 MB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 1.7/1.7 MB 53.5 MB/s eta 0:00:00
Collecting aws-cdk.aws-lambda==1.138.0
  Downloading aws_cdk.aws_lambda-1.138.0-py3-none-any.whl (510 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 510.4/510.4 kB 45.8 MB/s eta 0:00:00
Collecting aws-cdk.aws-route53==1.138.0
  Downloading aws_cdk.aws_route53-1.138.0-py3-none-any.whl (276 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 276.9/276.9 kB 32.6 MB/s eta 0:00:00
Collecting aws-cdk.aws-cloudwatch==1.138.0
  Downloading aws_cdk.aws_cloudwatch-1.138.0-py3-none-any.whl (305 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 305.5/305.5 kB 36.4 MB/s eta 0:00:00
Collecting aws-cdk.aws-iam==1.138.0
  Downloading aws_cdk.aws_iam-1.138.0-py3-none-any.whl (377 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 377.6/377.6 kB 36.1 MB/s eta 0:00:00
Collecting aws-cdk.aws-sns==1.138.0
  Downloading aws_cdk.aws_sns-1.138.0-py3-none-any.whl (109 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 109.9/109.9 kB 21.8 MB/s eta 0:00:00
Collecting aws-cdk.aws-route53-targets==1.138.0
  Downloading aws_cdk.aws_route53_targets-1.138.0-py3-none-any.whl (46 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 46.8/46.8 kB 9.8 MB/s eta 0:00:00
Collecting aws-cdk.aws-kms==1.138.0
  Downloading aws_cdk.aws_kms-1.138.0-py3-none-any.whl (132 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 132.4/132.4 kB 19.0 MB/s eta 0:00:00
Collecting aws-cdk.aws-events-targets==1.138.0
  Downloading aws_cdk.aws_events_targets-1.138.0-py3-none-any.whl (126 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 126.5/126.5 kB 16.1 MB/s eta 0:00:00
Collecting aws-cdk.aws-events==1.138.0
  Downloading aws_cdk.aws_events-1.138.0-py3-none-any.whl (245 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 245.0/245.0 kB 32.1 MB/s eta 0:00:00
Collecting aws-cdk.aws-autoscaling-common==1.138.0
  Downloading aws_cdk.aws_autoscaling_common-1.138.0-py3-none-any.whl (33 kB)
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.0.0-py3-none-any.whl (23 kB)
Collecting botocore<1.28.0,>=1.27.0
  Downloading botocore-1.27.5-py3-none-any.whl (8.9 MB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 8.9/8.9 MB 71.1 MB/s eta 0:00:00
Collecting s3transfer<0.7.0,>=0.6.0
  Downloading s3transfer-0.6.0-py3-none-any.whl (79 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 79.6/79.6 kB 17.5 MB/s eta 0:00:00
Collecting aws-cdk.aws-sns-subscriptions==1.138.0
  Downloading aws_cdk.aws_sns_subscriptions-1.138.0-py3-none-any.whl (40 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 40.8/40.8 kB 7.1 MB/s eta 0:00:00
Collecting aws-cdk.aws-acmpca==1.138.0
  Downloading aws_cdk.aws_acmpca-1.138.0-py3-none-any.whl (151 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 151.4/151.4 kB 28.4 MB/s eta 0:00:00
Collecting aws-cdk.assets==1.138.0
  Downloading aws_cdk.assets-1.138.0-py3-none-any.whl (25 kB)
Collecting aws-cdk.aws-codepipeline==1.138.0
  Downloading aws_cdk.aws_codepipeline-1.138.0-py3-none-any.whl (238 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 238.4/238.4 kB 32.9 MB/s eta 0:00:00
Collecting aws-cdk.aws-apigateway==1.138.0
  Downloading aws_cdk.aws_apigateway-1.138.0-py3-none-any.whl (806 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 806.1/806.1 kB 56.2 MB/s eta 0:00:00
Collecting aws-cdk.aws-stepfunctions==1.138.0
  Downloading aws_cdk.aws_stepfunctions-1.138.0-py3-none-any.whl (293 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 293.8/293.8 kB 38.7 MB/s eta 0:00:00
Collecting aws-cdk.custom-resources==1.138.0
  Downloading aws_cdk.custom_resources-1.138.0-py3-none-any.whl (151 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 151.0/151.0 kB 27.3 MB/s eta 0:00:00
Collecting aws-cdk.aws-kinesis==1.138.0
  Downloading aws_cdk.aws_kinesis-1.138.0-py3-none-any.whl (86 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 87.0/87.0 kB 17.2 MB/s eta 0:00:00
Collecting aws-cdk.aws-kinesisfirehose==1.138.0
  Downloading aws_cdk.aws_kinesisfirehose-1.138.0-py3-none-any.whl (263 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 263.9/263.9 kB 39.9 MB/s eta 0:00:00
Collecting aws-cdk.aws-codebuild==1.138.0
  Downloading aws_cdk.aws_codebuild-1.138.0-py3-none-any.whl (521 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 521.3/521.3 kB 57.2 MB/s eta 0:00:00
Collecting aws-cdk.aws-efs==1.138.0
  Downloading aws_cdk.aws_efs-1.138.0-py3-none-any.whl (117 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 117.1/117.1 kB 20.2 MB/s eta 0:00:00
Collecting aws-cdk.aws-codeguruprofiler==1.138.0
  Downloading aws_cdk.aws_codeguruprofiler-1.138.0-py3-none-any.whl (42 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 42.9/42.9 kB 9.0 MB/s eta 0:00:00
Collecting aws-cdk.aws-signer==1.138.0
  Downloading aws_cdk.aws_signer-1.138.0-py3-none-any.whl (46 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 46.5/46.5 kB 8.3 MB/s eta 0:00:00
Collecting aws-cdk.aws-globalaccelerator==1.138.0
  Downloading aws_cdk.aws_globalaccelerator-1.138.0-py3-none-any.whl (102 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 102.4/102.4 kB 20.9 MB/s eta 0:00:00
Collecting aws-cdk.aws-cognito==1.138.0
  Downloading aws_cdk.aws_cognito-1.138.0-py3-none-any.whl (467 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 467.8/467.8 kB 54.9 MB/s eta 0:00:00
Collecting aws-cdk.aws-cloudfront==1.138.0
  Downloading aws_cdk.aws_cloudfront-1.138.0-py3-none-any.whl (564 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 564.8/564.8 kB 48.7 MB/s eta 0:00:00
Collecting aws-cdk.aws-sam==1.138.0
  Downloading aws_cdk.aws_sam-1.138.0-py3-none-any.whl (245 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 246.0/246.0 kB 37.1 MB/s eta 0:00:00
Collecting aws-cdk.aws-codestarnotifications==1.138.0
  Downloading aws_cdk.aws_codestarnotifications-1.138.0-py3-none-any.whl (49 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 49.7/49.7 kB 9.7 MB/s eta 0:00:00
Collecting aws-cdk.aws-codecommit==1.138.0
  Downloading aws_cdk.aws_codecommit-1.138.0-py3-none-any.whl (86 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 86.5/86.5 kB 16.4 MB/s eta 0:00:00
Collecting aws-cdk.aws-cloudformation==1.138.0
  Downloading aws_cdk.aws_cloudformation-1.138.0-py3-none-any.whl (156 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 156.1/156.1 kB 26.6 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.25.4
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 139.0/139.0 kB 24.9 MB/s eta 0:00:00
Collecting python-dateutil<3.0.0,>=2.1
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 247.7/247.7 kB 38.4 MB/s eta 0:00:00
Collecting cattrs<22.2,>=1.8
  Downloading cattrs-22.1.0-py3-none-any.whl (33 kB)
Collecting typing-extensions<5.0,>=3.7
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting attrs~=21.2
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒劒 60.6/60.6 kB 12.8 MB/s eta 0:00:00
Collecting exceptiongroup
  Downloading exceptiongroup-1.0.0rc8-py3-none-any.whl (11 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: publication, urllib3, typing-extensions, six, PyYAML, jmespath, exceptiongroup, attrs, python-dateutil, cattrs, jsii, botocore, s3transfer, constructs, aws-cdk.region-info, aws-cdk.cloud-assembly-schema, boto3, aws-cdk.cx-api, aws-cdk.core, aws-cdk.aws-signer, aws-cdk.aws-sam, aws-cdk.aws-iam, aws-cdk.aws-codestarnotifications, aws-cdk.aws-acmpca, aws-cdk.assets, aws-cdk.aws-kms, aws-cdk.aws-events, aws-cdk.aws-codeguruprofiler, aws-cdk.aws-cloudwatch, aws-cdk.aws-autoscaling-common, aws-cdk.aws-ssm, aws-cdk.aws-sqs, aws-cdk.aws-s3, aws-cdk.aws-ecr, aws_cdk.aws_applicationautoscaling, aws-cdk.aws-sns, aws-cdk.aws-s3-assets, aws-cdk.aws-ecr-assets, aws-cdk.aws-codepipeline, aws_cdk.aws_logs, aws-cdk.aws-codecommit, aws-cdk.aws-stepfunctions, aws-cdk.aws-kinesis, aws-cdk.aws-ec2, aws-cdk.aws-elasticloadbalancing, aws-cdk.aws-efs, aws-cdk.aws-lambda, aws-cdk.aws-sns-subscriptions, aws-cdk.aws-secretsmanager, aws-cdk.aws-kinesisfirehose, aws-cdk.aws-cloudformation, aws-cdk.custom-resources, aws-cdk.aws-codebuild, aws-cdk.aws-route53, aws-cdk.aws-globalaccelerator, aws-cdk.aws-certificatemanager, aws-cdk.aws-elasticloadbalancingv2, aws-cdk.aws-cognito, aws-cdk.aws-cloudfront, aws-cdk.aws-servicediscovery, aws-cdk.aws-autoscaling, aws-cdk.aws-apigateway, aws-cdk.aws-route53-targets, aws-cdk.aws-autoscaling-hooktargets, aws-cdk.aws-ecs, aws-cdk.aws-events-targets, aws_cdk.aws_ecs_patterns
Successfully installed PyYAML-6.0 attrs-21.4.0 aws-cdk.assets-1.138.0 aws-cdk.aws-acmpca-1.138.0 aws-cdk.aws-apigateway-1.138.0 aws-cdk.aws-autoscaling-1.138.0 aws-cdk.aws-autoscaling-common-1.138.0 aws-cdk.aws-autoscaling-hooktargets-1.138.0 aws-cdk.aws-certificatemanager-1.138.0 aws-cdk.aws-cloudformation-1.138.0 aws-cdk.aws-cloudfront-1.138.0 aws-cdk.aws-cloudwatch-1.138.0 aws-cdk.aws-codebuild-1.138.0 aws-cdk.aws-codecommit-1.138.0 aws-cdk.aws-codeguruprofiler-1.138.0 aws-cdk.aws-codepipeline-1.138.0 aws-cdk.aws-codestarnotifications-1.138.0 aws-cdk.aws-cognito-1.138.0 aws-cdk.aws-ec2-1.138.0 aws-cdk.aws-ecr-1.138.0 aws-cdk.aws-ecr-assets-1.138.0 aws-cdk.aws-ecs-1.138.0 aws-cdk.aws-efs-1.138.0 aws-cdk.aws-elasticloadbalancing-1.138.0 aws-cdk.aws-elasticloadbalancingv2-1.138.0 aws-cdk.aws-events-1.138.0 aws-cdk.aws-events-targets-1.138.0 aws-cdk.aws-globalaccelerator-1.138.0 aws-cdk.aws-iam-1.138.0 aws-cdk.aws-kinesis-1.138.0 aws-cdk.aws-kinesisfirehose-1.138.0 aws-cdk.aws-kms-1.138.0 aws-cdk.aws-lambda-1.138.0 aws-cdk.aws-route53-1.138.0 aws-cdk.aws-route53-targets-1.138.0 aws-cdk.aws-s3-1.138.0 aws-cdk.aws-s3-assets-1.138.0 aws-cdk.aws-sam-1.138.0 aws-cdk.aws-secretsmanager-1.138.0 aws-cdk.aws-servicediscovery-1.138.0 aws-cdk.aws-signer-1.138.0 aws-cdk.aws-sns-1.138.0 aws-cdk.aws-sns-subscriptions-1.138.0 aws-cdk.aws-sqs-1.138.0 aws-cdk.aws-ssm-1.138.0 aws-cdk.aws-stepfunctions-1.138.0 aws-cdk.cloud-assembly-schema-1.138.0 aws-cdk.core-1.138.0 aws-cdk.custom-resources-1.138.0 aws-cdk.cx-api-1.138.0 aws-cdk.region-info-1.138.0 aws_cdk.aws_applicationautoscaling-1.138.0 aws_cdk.aws_ecs_patterns-1.138.0 aws_cdk.aws_logs-1.138.0 boto3-1.24.0 botocore-1.27.5 cattrs-22.1.0 constructs-3.4.32 exceptiongroup-1.0.0rc8 jmespath-1.0.0 jsii-1.60.0 publication-0.0.3 python-dateutil-2.8.2 s3transfer-0.6.0 six-1.16.0 typing-extensions-4.2.0 urllib3-1.26.9
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
$ cdk synth test-jsii-cdk
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                  !!
!!  Node v13.7.0 has reached end-of-life and is not supported.                      !!
!!  You may to encounter runtime issues, and should switch to a supported release.  !!
!!                                                                                  !!
!!  As of the current release, supported versions of node are:                      !!
!!  - ^12.7.0                                                                       !!
!!  - ^14.5.0                                                                       !!
!!  - ^16.3.0                                                                       !!
!!                                                                                  !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(node:89) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
b'/tmp/tmpk6vtoupd/bin/jsii-runtime.js:3666\n'
b'                this.untested = opts.untested ?? false;\n'
b'                                               ^\n'
b'\n'
b"SyntaxError: Unexpected token '?'\n"
b'    at wrapSafe (internal/modules/cjs/loader.js:1067:16)\n'
b'    at Module._compile (internal/modules/cjs/loader.js:1115:27)\n'
b'    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)\n'
b'    at Module.load (internal/modules/cjs/loader.js:1000:32)\n'
b'    at Function.Module._load (internal/modules/cjs/loader.js:899:14)\n'
b'    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n'
b'    at internal/main/run_main_module.js:17:47\n'
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from aws_cdk import core
  File "/usr/local/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 939, in <module>
    from ._jsii import *
  File "/usr/local/lib/python3.8/site-packages/aws_cdk/core/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.cloud_assembly_schema._jsii
  File "/usr/local/lib/python3.8/site-packages/aws_cdk/cloud_assembly_schema/__init__.py", line 75, in <module>
    from ._jsii import *
  File "/usr/local/lib/python3.8/site-packages/aws_cdk/cloud_assembly_schema/_jsii/__init__.py", line 11, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/usr/local/lib/python3.8/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 269, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 338, in load
    return self._process.send(request, LoadResponse)
  File "/usr/local/lib/python3.8/site-packages/jsii/_utils.py", line 24, in wrapped
    stored.append(fgetter(self))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 333, in _process
    process.start()
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 275, in start
    self.handshake()
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 299, in handshake
    self._next_message(), _HelloResponse
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 242, in _next_message
    return json.loads(self._process.stdout.readline(), object_hook=ohook)
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 284, in stop
    self._process.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
Subprocess exited with error 1
```

### SDK version used

CDK

### Environment details (OS name and version, etc.)

docker image:  justincasetech/aws-cdk:1.22.0-python3.8.1

**Comment by zhangwenjia0326** [comment]
Experiencing exact same issue. Any proposed short term fixes? Thanks!

**Comment by codeforkjeff** [comment]
I'm experiencing this as well.

**Comment by putty56** [comment]
the issue derives from the support of nullish coalescing assignment operator (??) in node versions prior to 14.5

One way to get around it is setting the jsii to an earlier version. In my case it was blowing up when building in AWS CodeBuild. The only way to get around it in that instance is to change your build machine to Linux Ubuntu, standard:5.0 that image has support for 14.5, or if you are using a custom image just need to set your node version to 14.5 or higher

**Comment by peterwoodworth** [comment]
This should be fixed in latest jsii release https://github.com/aws/jsii/releases/tag/v1.60.1

Let me know if not

**Comment by liubo20210831** [comment]
@peterwoodworth
This time it is `jsii-1.60.1`, but errors continue to appear
 ```log
Installing collected packages: publication, urllib3, typing-extensions, six, PyYAML, jmespath, exceptiongroup, attrs, python-dateutil, cattrs, jsii, botocore, s3transfer, constructs, aws-cdk.region-info, aws-cdk.cloud-assembly-schema, boto3, aws-cdk.cx-api, aws-cdk.core, aws-cdk.aws-signer, aws-cdk.aws-sam, aws-cdk.aws-iam, aws-cdk.aws-codestarnotifications, aws-cdk.aws-acmpca, aws-cdk.assets, aws-cdk.aws-kms, aws-cdk.aws-events, aws-cdk.aws-codeguruprofiler, aws-cdk.aws-cloudwatch, aws-cdk.aws-autoscaling-common, aws-cdk.aws-ssm, aws-cdk.aws-sqs, aws-cdk.aws-s3, aws-cdk.aws-ecr, aws_cdk.aws_applicationautoscaling, aws-cdk.aws-sns, aws-cdk.aws-s3-assets, aws-cdk.aws-ecr-assets, aws-cdk.aws-codepipeline, aws_cdk.aws_logs, aws-cdk.aws-codecommit, aws-cdk.aws-stepfunctions, aws-cdk.aws-kinesis, aws-cdk.aws-ec2, aws-cdk.aws-elasticloadbalancing, aws-cdk.aws-efs, aws-cdk.aws-lambda, aws-cdk.aws-sns-subscriptions, aws-cdk.aws-secretsmanager, aws-cdk.aws-kinesisfirehose, aws-cdk.aws-cloudformation, aws-cdk.custom-resources, aws-cdk.aws-codebuild, aws-cdk.aws-route53, aws-cdk.aws-globalaccelerator, aws-cdk.aws-certificatemanager, aws-cdk.aws-elasticloadbalancingv2, aws-cdk.aws-cognito, aws-cdk.aws-cloudfront, aws-cdk.aws-servicediscovery, aws-cdk.aws-autoscaling, aws-cdk.aws-apigateway, aws-cdk.aws-route53-targets, aws-cdk.aws-autoscaling-hooktargets, aws-cdk.aws-ecs, aws-cdk.aws-events-targets, aws_cdk.aws_ecs_patterns
Successfully installed PyYAML-6.0 attrs-21.4.0 aws-cdk.assets-1.138.0 aws-cdk.aws-acmpca-1.138.0 aws-cdk.aws-apigateway-1.138.0 aws-cdk.aws-autoscaling-1.138.0 aws-cdk.aws-autoscaling-common-1.138.0 aws-cdk.aws-autoscaling-hooktargets-1.138.0 aws-cdk.aws-certificatemanager-1.138.0 aws-cdk.aws-cloudformation-1.138.0 aws-cdk.aws-cloudfront-1.138.0 aws-cdk.aws-cloudwatch-1.138.0 aws-cdk.aws-codebuild-1.138.0 aws-cdk.aws-codecommit-1.138.0 aws-cdk.aws-codeguruprofiler-1.138.0 aws-cdk.aws-codepipeline-1.138.0 aws-cdk.aws-codestarnotifications-1.138.0 aws-cdk.aws-cognito-1.138.0 aws-cdk.aws-ec2-1.138.0 aws-cdk.aws-ecr-1.138.0 aws-cdk.aws-ecr-assets-1.138.0 aws-cdk.aws-ecs-1.138.0 aws-cdk.aws-efs-1.138.0 aws-cdk.aws-elasticloadbalancing-1.138.0 aws-cdk.aws-elasticloadbalancingv2-1.138.0 aws-cdk.aws-events-1.138.0 aws-cdk.aws-events-targets-1.138.0 aws-cdk.aws-globalaccelerator-1.138.0 aws-cdk.aws-iam-1.138.0 aws-cdk.aws-kinesis-1.138.0 aws-cdk.aws-kinesisfirehose-1.138.0 aws-cdk.aws-kms-1.138.0 aws-cdk.aws-lambda-1.138.0 aws-cdk.aws-route53-1.138.0 aws-cdk.aws-route53-targets-1.138.0 aws-cdk.aws-s3-1.138.0 aws-cdk.aws-s3-assets-1.138.0 aws-cdk.aws-sam-1.138.0 aws-cdk.aws-secretsmanager-1.138.0 aws-cdk.aws-servicediscovery-1.138.0 aws-cdk.aws-signer-1.138.0 aws-cdk.aws-sns-1.138.0 aws-cdk.aws-sns-subscriptions-1.138.0 aws-cdk.aws-sqs-1.138.0 aws-cdk.aws-ssm-1.138.0 aws-cdk.aws-stepfunctions-1.138.0 aws-cdk.cloud-assembly-schema-1.138.0 aws-cdk.core-1.138.0 aws-cdk.custom-resources-1.138.0 aws-cdk.cx-api-1.138.0 aws-cdk.region-info-1.138.0 aws_cdk.aws_applicationautoscaling-1.138.0 aws_cdk.aws_ecs_patterns-1.138.0 aws_cdk.aws_logs-1.138.0 boto3-1.24.6 botocore-1.27.6 cattrs-22.1.0 constructs-3.4.33 exceptiongroup-1.0.0rc8 jmespath-1.0.0 jsii-1.60.1 publication-0.0.3 python-dateutil-2.8.2 s3transfer-0.6.0 six-1.16.0 typing-extensions-4.2.0 urllib3-1.26.9
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
$ cdk synth test-jsii-cdk
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                                                  !!
!!  Node v13.7.0 has reached end-of-life and is not supported.                      !!
!!  You may to encounter runtime issues, and should switch to a supported release.  !!
!!                                                                                  !!
!!  As of the current release, supported versions of node are:                      !!
!!  - ^12.7.0                                                                       !!
!!  - ^14.5.0                                                                       !!
!!  - ^16.3.0                                                                       !!
!!                                                                                  !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(node:89) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
b'/tmp/tmpzk_3ywvc/bin/jsii-runtime.js:3843\n'
b'            process.exit(128 + (os_1.constants.signals[signal] ?? 0));\n'
b'                                                                ^\n'
b'\n'
b"SyntaxError: Unexpected token '?'\n"
b'    at wrapSafe (internal/modules/cjs/loader.js:1067:16)\n'
b'    at Module._compile (internal/modules/cjs/loader.js:1115:27)\n'
b'    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)\n'
b'    at Module.load (internal/modules/cjs/loader.js:1000:32)\n'
b'    at Function.Module._load (internal/modules/cjs/loader.js:899:14)\n'
b'    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n'
b'    at internal/main/run_main_module.js:17:47\n'
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from aws_cdk import core
  File "/usr/local/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 939, in <module>
    from ._jsii import *
  File "/usr/local/lib/python3.8/site-packages/aws_cdk/core/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.cloud_assembly_schema._jsii
  File "/usr/local/lib/python3.8/site-packages/aws_cdk/cloud_assembly_schema/__init__.py", line 75, in <module>
    from ._jsii import *
  File "/usr/local/lib/python3.8/site-packages/aws_cdk/cloud_assembly_schema/_jsii/__init__.py", line 11, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "/usr/local/lib/python3.8/site-packages/jsii/_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/__init__.py", line 269, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 338, in load
    return self._process.send(request, LoadResponse)
  File "/usr/local/lib/python3.8/site-packages/jsii/_utils.py", line 24, in wrapped
    stored.append(fgetter(self))
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 333, in _process
    process.start()
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 275, in start
    self.handshake()
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 299, in handshake
    self._next_message(), _HelloResponse
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 242, in _next_message
    return json.loads(self._process.stdout.readline(), object_hook=ohook)
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/jsii/_kernel/providers/process.py", line 284, in stop
    self._process.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
Subprocess exited with error 1
```

**Comment by udondan** [comment]
confirming. 1.60.1 still failed for me. updating to latest superchain solved it of course.

**Comment by ayachnes2** [comment]
@liubo20210831 

I was in a similar situation as you except I was using CDK with Java. I got similar errors when downgrading `jsii` to 1.59.0. This was happening because of the transient dependency `software.constructs:constructs:3.4.32`, which is a breaking minor version change for node 12. Downgrading the maven dependency `software.constructs:constructs:3.4.32` to `software.constructs:constructs:3.4.31` fixed the issue.

So, in summary, I can confirm that the following works with node 12.22.12:
1. Downgrade `jsii` (`jsii-runtime` maven dependency) to 1.59.0
2. Downgrade `software.constructs:constructs` to 3.4.31

**Comment by liubo20210831** [comment]
> @liubo20210831
> 
> I was in a similar situation as you except I was using CDK with Java. I got similar errors when downgrading `jsii` to 1.59.0. This was happening because of the transient dependency `software.constructs:constructs:3.4.32`, which is a breaking minor version change for node 12. Downgrading the maven dependency `software.constructs:constructs:3.4.32` to `software.constructs:constructs:3.4.31` fixed the issue.
> 
> So, in summary, I can confirm that the following works with node 12.22.12:
> 
> 1. Downgrade `jsii` (`jsii-runtime` maven dependency) to 1.59.0
> 2. Downgrade `software.constructs:constructs` to 3.4.31

Thank you for your explanation. At present, I have also downgraded to jsii-1.59.0 to keep the CDK program running.

**Comment by RomainMuller** [comment]
The import part of the warning message is:

```
Node v13.7.0 has reached end-of-life and is not supported.  
```

If you get `SyntaxError: Unexpected token '?'` it means you are using node `< 14.5.0`, which has been end-of-life since *at least* 2021-04-30.

The fix I introduced in `1.60.1` was solely to make `@jsii/check-node` successfully print out the message informing users they are on an unsupported node runtime and need to upgrade.

Note that the Node 16 deprecation has also been moved forward (it depends on OpenSSL 1.1, which EOLs later this year). I would STRONGLY recommend upgrading to Node 18 if possible (it also seems to be quite a bit faster).
